---
stages:
  - test
  - docs

run-tests:
  stage: test
  script:
    - "python -m venv /opt/venv"
    - "source /opt/venv/bin/activate; pip install --upgrade pip"
    - "source /opt/venv/bin/activate; pip install -e ."
    - "source /opt/venv/bin/activate; tox -rs test"
